name = "TestPkgs"
uuid = "e9ff2660-48f5-44fc-b7eb-8142a6480195"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
KangarooTwelve = "2a5dabf5-6a39-42aa-818d-ce8a58d1b312"

[targets]
test = ["Test", "Jive", "KangarooTwelve"]

[compat]
Jive = "0.3"
KangarooTwelve = "1.0"
